version: '3.8'

services:
  db:
    networks:
      - bordados
    container_name: bordados
    image: 'postgres:alpine'
    ports:
      - 5432:5432
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: '10'
    volumes:
      - 'db:/var/lib/postgresql/data'
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  db: null

networks:
  bordados: null
